name: wine-quality-reliability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - scipy
  - pip
  - jupyter
  - pip:
      - xgboost
      - shap
      - torch
      - pytorch-tabnet
      - imbalanced-learn
